# Generated by Django 2.2.6 on 2019-10-27 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livedata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usershift',
            name='checked_in',
            field=models.CharField(max_length=17),
        ),
    ]
