# Generated by Django 2.2.6 on 2019-10-27 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livedata', '0002_auto_20191027_0416'),
    ]

    operations = [
        migrations.AddField(
            model_name='usershift',
            name='year_in_school',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior')], default='JR', max_length=2),
        ),
    ]
