# Generated by Django 2.2.6 on 2019-10-27 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livedata', '0004_auto_20191027_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usershift',
            name='checked_in',
            field=models.CharField(choices=[('FR', 'Checked In'), ('SO', 'Declined'), ('JR', 'Awaiting Response')], default='JR', max_length=2),
        ),
    ]
