# Generated by Django 2.2.6 on 2019-10-27 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livedata', '0005_auto_20191027_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usershift',
            name='checked_in',
            field=models.CharField(choices=[('CI', 'Checked In'), ('DE', 'Declined'), ('AR', 'Awaiting Response')], default='AR', max_length=2),
        ),
    ]
