# Generated by Django 2.2.6 on 2019-10-27 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='zone',
            field=models.IntegerField(default=-1),
        ),
    ]
