version: "3.3"
services:
  # database backend for the web app
  postgres:
    image: postgres
    environment:
        POSTGRES_PASSWORD: crosswatch
        POSTGRES_USER: crosswatch
        POSTGRES_DB: crosswatch
    volumes:
    - db-data:/var/lib/postgresql/data
    ports:
    - 5432:5432
    networks: 
      - crosswatch-dev
  
  # key value store for pub/sub when pushing to the map UI
  redis:
    image: "redis:alpine"
    volumes:
      - 'redis-data:/data'
    ports:
      - 6379:6379
    networks: 
      - crosswatch-dev

volumes:
  db-data:
    driver: local
  redis-data:
    driver: local

networks:
  crosswatch-dev:
    driver: bridge