#!/bin/bash
set -ex

# Build the image with new dependencies installed and new lockfile generated
pushd "$(git rev-parse --show-toplevel)/docker/dev/environment/" 
    sh docker_build
popd


APP="$(git rev-parse --show-toplevel)/ACGCrossingApp"

# Run a container from the image and update the lockfile in our local git project
docker run \
    --mount type=bind,source=${APP},target=/live-app \
    crosswatch-dev-environment:latest pipfile
